export const M = {
  TITLEFONT: "Josefin Sans, sans-serif",
  FONT: "Roboto, sans-serif",
  JUANA_FONT: "Juana, serif",
  MOBILESWITCH: 922, // Pixels below which is mobile.
  LEFTPRODUCTSWITCH: 500,
  COOKIEMESSAGEKEY: "cookie_message",
  COOKIEPATH: "/",
  REFERRAL_COOKIE_KEY: "referral_code",
  CREATOR_CODE_COOKIE_KEY: "creator_code",
  PRO_CODE_COOKIE_KEY: "pro_code",
  HAS_AI_SEARCH: "has_ai_search",
  MENUSWITCH: 768,
  MINWIDTH: "320px",
  MAXWIDTH: "1000px",
  COL: {
    BG: {
      BLACK: "#000000",
      MID: "#EFEFEF",
      GREY: "#F5F5F5",
      LIGHT: "#FBFBFB",
      WHITE: "#FFFFFF",
      DARKBLUE: "#140C40",
      DARKGREEN: "#1B4B2E",
      DARKPURPLE: "#540E3C",
      LOGIN: "#333333",
    },
    TEXT: {
      BLACK: "#000000",
      MID: "#707070",
      LIGHT: "#888888",
      WHITE: "#FFFFFF",
      YELLOW: "#FDCA47",
      ERROR: "#AE1A26",
      ERRORDARK: "#990000",
      GREEN: "#2A8539",
    },
    BUTTON: {
      BLACK: "#000000",
      DARKGREY: "#303030",
      MIDDARK: "#707070",
      MID: "#EFEFEF",
      LIGHT: "#888888",
      WHITE: "#FFFFFF",
      YELLOW: "#FDCA47",
      MIDYELLOW: "#FEDF91",
      LIGHTYELLOW: "#FEEAB5",
      TRANSPARENT_WHITE: "#FFFFFFBA",
      TRANSPARENT_BLACK: "#000000C2",
    },
    LINE: {
      MID: "#CECFD1",
      YELLOW: "#FDCA47",
    },
    UPDATECOLS: {
      GREEN: "#70a96f",
      ORANGE: "#ff7f2a",
      RED: "#c83737",
      GREY: "#888888",
    },
    UC: {
      FG: "#FF0000",
      BG: "#FFDDDD",
    },
  },
  HEIGHTS: {
    TOPMENU: "56px",
  },
};
